### PR TITLE
Feature/pipedrive

### PR DESCRIPTION
**Pull request by alecklandgraf**
Pipedrive CRM Web Hook Push Notification Plugin for Will.

Quickstart
    To use the Pipedrive Plugin:
        1. set your Pipedrive API Key in your env or Will's config.py as PIPEDRIVE_KEY or (recommended)in the
        environment as WILL_PIPEDRIVE_KEY
        2. create a push notification subscription at https://<your-org>.pipedrive.com/push_notifications/index#
        3. add any pipelines or stages to the whitelists and blacklists below in config.py by id
            - ex. PIPEDRIVE_PIPELINE_WHITELIST = [1, 7]

```
Will will notify its default chat room when a deal is moved from one stage to another, won, or lost.
```

Optional config.py settings:
    PIPEDRIVE_PIPELINE_WHITELIST - only pipeline ids on the whitelist trigger notifications
    PIPEDRIVE_STAGE_WHITELIST - only stages on the whiltelist will trigger notifications
    PIPEDRIVE_PIPELINE_BLACKLIST - pipeline ids on the blacklist will not trigger notifications (overides whitelist)
    PIPEDRIVE_STAGE_BLACKLIST - stage ids on the blacklist will not trigger notifications (overides whitelist)

image

### CODE REVIEW

**Comment by alecklandgraf** [comment]
@afrojet updated my copy 
image

**Comment by alecklandgraf** [comment]
@skoczen ready for CR, also needs the Pipeline API key added to the env.

**Comment by alecklandgraf** [comment]
Finished my read through, looks good to me.

**Comment by skoczen** [comment]
CR G2G, looks great!

**Comment by alecklandgraf** [comment]
@skoczen can you confirm you added the `WILL_PIPEDRIVE_KEY` to the heroku config? 
I think this should be done before merging since that will trigger the deploy.

Thanks,
-Aleck

**Pull request merged**
